#!/usr/bin/env python3

# main file for running other stuff
from src.argparser import parser
from src.autocompile import autocompile
from src.autorun import autoRun
from collections import defaultdict

commands = {'compile': autocompile, 'run': autoRun}

args = parser.parse_args()
if (args.command in commands):
    options = defaultdict(
        lambda: None, {'input': args.input, 'output': args.output})

    progArgs = args.args if args.args else []
    commands[args.command](args.program, progArgs, options=options)
else:
    print('Unknown command', args.command)

# print("found args: ", args)
